version: '3.8'
services:
  backend:
    build: ./backend
    env_file:
      - backend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
  db:
    image: "postgres:13-alpine" 
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
volumes:
  db_data:
 
 


 
